# Site settings
title: Gamma Building
email: enquire@gammabuilding.co.nz
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://www.gammabuilding.co.nz   # with the https protocol
enforce_ssl: gammabuilding.co.nz   # without any protocol

# User setting
owner: Gamma Building
email: enquire@gammabuilding.co.nz
facebook_username: Gamma Building
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone: 027 3131 229 or 027 2322 585
copyright:

# API settings
google_api_key: AIzaSyB1JaYu5_C-tU2vNDTaeAR-Gu873Y7pPqM

# Build settings
markdown: kramdown