# Site settings
title: Gamma Building
email: enquire@gammabuilding.co.nz
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://www.gammabuilding.co.nz   # with the https protocol SSL instructions- https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/
enforce_ssl: gammabuilding.co.nz   # without any protocol

# User setting
owner: Simon Alsford & Aaron Huddleston
email: enquire@gammabuilding.co.nz
facebook_username: Gamma-Building-1525530924416973
twitter_username:
exclude: [node_modules]
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone_simon: 027 3131 229
telephone_aaron: 027 2322 585
copyright:

# API settings
google_api_key: AIzaSyB1JaYu5_C-tU2vNDTaeAR-Gu873Y7pPqM

# Build settings
markdown: kramdown